fix(glibc): Remove external linker from ldflags, add netgo tag

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -1,7 +1,7 @@
 name: golangci-lint
 on:
   pull_request:
-   paths-ignore:
+    paths-ignore:
       - 'README.md'
       - '*_test.go'
 jobs:
@@ -9,7 +9,6 @@ jobs:
     strategy:
       matrix:
         go-version: [1.22.x]
-        # os: [ubuntu-latest]
         os: [ubuntu-latest, macos-latest, windows-latest]
     name: lint
     runs-on: ${{ matrix.os }}
@@ -18,13 +17,26 @@ jobs:
       - uses: actions/setup-go@v5
         with:
           go-version: ${{ matrix.go-version }}
+
+      - name: Check for Cgo dependencies
+        run: |
+          echo "Searching for packages that require Cgo..."
+          CGO_PACKAGES=$(go list -f '{{if .CgoFiles}}{{.ImportPath}}{{end}}' -tags cgo ./...)
+          if [ -n "$CGO_PACKAGES" ]; then
+            echo "::error::Found packages that require Cgo, which is not allowed."
+            echo "This will result in a dynamically linked binary."
+            echo "The following packages must be removed or refactored:"
+            echo "$CGO_PACKAGES"
+            # Exit with a non-zero status to fail the workflow
+            exit 1
+          else
+            echo "Success: No Cgo dependencies found."
+          fi
+
       - name: golangci-lint
         uses: golangci/golangci-lint-action@v6
         with:
           version: v1.63
-
-          # Optional: golangci-lint command line arguments.
           args: --timeout=5m
-
-          # Optional: show only new issues if it's a pull request. The default value is `false`.
           only-new-issues: true
+
